# Numpy library


Biblioteca principal para computación científica en Python.
Proporciona un objeto de arreglo multidimensional de alto rendimiento
y herramientas para trabajar con estos arreglos.

1. Numeric Python (Python numérico)
2. Cálculos sobre arreglos completos (operaciones vectorizadas)
3. Muy eficiente
4. Álgebra lineal

TEN EN CUENTA / ¡IMPORTANTE!:

- ¡Solo puede contener valores del mismo tipo! (homogéneo)
- El operador + se comporta de forma diferente que con las listas normales!

In [1]:
import numpy as np

scores = [24, 23, 30, 29, 17, 16, 15]

np_scores = np.array(scores)

print(np_scores)  

print(scores*2)
print(np_scores*2)

#print(np_scores) 
print(np_scores+1)  

print(type(scores))
print(type(np_scores))

[24 23 30 29 17 16 15]
[24, 23, 30, 29, 17, 16, 15, 24, 23, 30, 29, 17, 16, 15]
[48 46 60 58 34 32 30]
[25 24 31 30 18 17 16]
<class 'list'>
<class 'numpy.ndarray'>


In [2]:
#trabajando la lista
np_scores[3:-2]
# podemos convertirlo en una lista
#np_scores_list=np_scores.tolist()
#np_scores_list[:4]

array([29, 17])

In [3]:
## subsetting específicamente con numpy 
np_scores >= 18

array([ True,  True,  True,  True, False, False, False])

In [4]:
np_scores[np_scores>=18]

array([24, 23, 30, 29])

# 2D Numpy arrays

In [ ]:
scores_1 = [24, 23, 30, 29, 17, 16, 15]
scores_2 = [15, 26, 24, 25, 18, 30, 23]

In [ ]:
np_2d_scores = np.array([scores_1,scores_2])

In [ ]:
np_2d_scores  #como lista de listas

In [ ]:
np_2d_scores.shape  

In [ ]:
np_2d_scores[0][2]
np_2d_scores[0,2]

In [ ]:
np_2d_scores[:,1:3] #todas las columnas

In [ ]:
np_2d_scores[1,:] #todas las columnas y primera fila

## Loop on a numpy array

In [ ]:
for score in scores: 
    print(score)

In [ ]:
for score in np_2d_scores: #no funciona para 2d
    print(score)


In [ ]:
for val in np.nditer(np_2d_scores):
    print(val) 

In [ ]:
for row in np_2d_scores:
    for x in row:
        print(x)

## Podemos ir más allá

In [ ]:
np_2d_scores_2 = np_2d_scores*2
np_2d_scores_2 

In [ ]:
np_3d_scores=[np_2d_scores,np_2d_scores_2]  

In [ ]:
np_3d_scores

In [ ]:
np.shape(np_3d_scores)

In [ ]:
np_3d_scores[0][1][3]
np_3d_scores[1][:,1]